### ISSUE TITLE
修改WriteData的代码，里面有bug

### ISSUE THREAD

**Issue by Afeather2017** [HuiyuanYan/FAT12-File-System#1]
FAT12.c的512行
do { 
} while (tmpClus & 0xFFF != 0xFFF);

这里先执行0xFFF != 0xFFF再执行&。

你的代码出现在我们的割头(www.educoder.com)实验中了。

**Comment by HuiyuanYan** [comment]
感谢issue。顺便能问下具体的头歌网页吗？我这个项目写着玩的哈哈，等有时间重构一下！

**Comment by Afeather2017** [comment]
你有帐号不？割头的帐号

**Comment by Afeather2017** [comment]
我可以直接把你拉到我们的课程里

**Comment by Afeather2017** [comment]
邀请码：7TFOY

**Comment by HuiyuanYan** [comment]
哈哈，感谢了！&nbsp;


dio
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月31日(星期二) 晚上8:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HuiyuanYan/FAT12-File-System] 修改WriteData的代码，里面有bug (Issue #1)





 
邀请码：7TFOY

**Comment by Afeather2017** [comment]
![Uploading image.png…]()
你是这个帐号？

**Comment by Afeather2017** [comment]
你是plo7rihsu这个帐号？

**Comment by HuiyuanYan** [comment]
不是，我是刘华强那个头像的




dio
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HuiyuanYan/FAT12-File-System"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月31日(星期二) 晚上8:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HuiyuanYan/FAT12-File-System] 修改WriteData的代码，里面有bug (Issue #1)





 
你是plo7rihsu这个帐号？
